language: android
android:
    components:
        - platform-tools
        - tools
        - build-tools-24.0.2
        - android-24
        - sys-img-x86-android-23
        - sys-img-x86-android-24
